### ISSUE TITLE
where to find ground truth of 3d

### ISSUE THREAD

**Issue by openmaker** [anibali/h36m-fetch#10]
i decoded h36m dataset to h5 format, for each data subset, there are 4 views and 500 images per view, 2000 images totally.
on hdf viewer(to read the data inside h5 file), i can see 2000_32_2 for 2d, and 2000_32_3 for 3d, so my question is where to find ground truth of 3d joint points, in my understanding, it should be 500_32_3 for 3d, am i right or wrong?

**Comment by anibali** [comment]
The count of 2000 is correct for `/pose/3d`, since it has pose data for all 4 cameras. You can find which camera each pose applies to by referencing `/camera`.

**Comment by openmaker** [comment]
do you know the data structure of h36m as well as the 3d joint dataset?

**Comment by zhoushiwei** [comment]
> i decoded h36m dataset to h5 format, for each data subset, there are 4 views and 500 images per view, 2000 images totally.
> on hdf viewer(to read the data inside h5 file), i can see 2000_32_2 for 2d, and 2000_32_3 for 3d, so my question is where to find ground truth of 3d joint points, in my understanding, it should be 500_32_3 for 3d, am i right or wrong?

hi, can you send me the h36m dataset , I have send email to the site, but no one reply me

**Comment by openmaker** [comment]
@zhoushiwei the size of it is ~60G, too big to send, but if you want data for single view training, please find it at,
https://pan.baidu.com/s/16sOXYqw8n7EkB9Qy2Z8HfA code:cm1j

**Comment by openmaker** [comment]
@anibali How to find pose angles? in the annot.h5?

**Comment by openmaker** [comment]
How can I find the pose_angles keys? Now we cannot find the pose_angles, which is provided by H3.6M under label name of angles, in the generated annot.h5. Thank you.

**Comment by anibali** [comment]
Angles are currently not stored in the annot.h5 file.

**Comment by zhoushiwei** [comment]
Hi, it’s only image?don’t have the 3D data?

**Comment by anibali** [comment]
This issue has drifted way off topic. @zhoushiwei please use the official website to obtain the dataset, or discuss it elsewhere.
