### ISSUE TITLE
How long will it take for getting account been approved?

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [anibali/h36m-fetch#11]
Dear anibali: 
    Could you tell me that how long did it take you to get your account approved? Because some people said that they haven't get the account approved from several months ago. Thank you very much!

**Comment by anibali** [comment]
It definitely didn't take me several months. Maybe a couple of weeks or so? Just to be clear, I don't have any special contact or affiliation with the Human3.6M team, so I went through the same process as everyone else.

**Comment by Ixiaohuihuihui** [comment]
Thank you very much! I will wait patiently^_^

**Comment by li19960612** [comment]
@Ixiaohuihuihui Have you received this dataset? I just have not get the account verified from several months ago.

**Comment by Ixiaohuihuihui** [comment]
> @Ixiaohuihuihui Have you received this dataset? I just have not get the account verified from several months ago.

Yes, I have.

**Comment by huangchaoxing** [comment]
> @Ixiaohuihuihui Have you received this dataset? I just have not get the account verified from several months ago.

Did you get approved ?
