### ISSUE TITLE
process_all.py error

### ISSUE THREAD

**Issue by diazdaiz** [anibali/h36m-fetch#18]
when i try to run process_all.py, i got this error message: "spacepy.pycdf.CDFError: NO_SUCH_CDF: The specified CDF does not exist", i already install the requirements.txt using pip, can someone help me please

**Comment by siehlema** [comment]
I had a similar error "Exception: Cannot load CDF C library".

After checking the Dockerfile instructions I installed the CDF library with the given commands. This helped me solve this issue. Maybe you are also missing the CDF library?

**Comment by diazdaiz** [comment]
thanks, it work for me now
