### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by Fangyh09** [anibali/h36m-fetch#2]
Hi, I run the script but encounter the problem that,
```
missing data for S11/WalkingDog.54138969
missing data for S11/WalkingDog.55011271
missing data for S11/WalkingDog.58860488
missing data for S11/WalkingDog.60457274
```

**Comment by anibali** [comment]
Yes, this is just an anomaly with the dataset, I get the same (a small part of the data appears to be missing from the official downloads). You can safely ignore the messages.

**Comment by anibali** [comment]
I have discovered that the original dataset actually does contain this data, but there is inconsistent naming between "WalkDog" and "WalkingDog" which was causing my script to miss it. PR https://github.com/anibali/h36m-fetch/pull/4 will fix this issue as a byproduct.
