### ISSUE TITLE
What is the data structure and meaning of Poses_D2_Positions_S1

### ISSUE THREAD

**Issue by Droliven** [anibali/h36m-fetch#20]
I downloaded Poses_D2_Positions_S1 from the official website of human3.6m. After parsing, I got an array of 1x1383x64. I wonder if this means that these data have 1383 frames each containing 32 key points. If so, I would like to know what are the positions of these 32 key points?

**Comment by anibali** [comment]
Yes it means that there are 32 2D coordinates for each frame. The code I use to read an reshape this data is here: https://github.com/anibali/h36m-fetch/blob/b85e69bb446d5dd87b7461a162a6332654718f3a/process_all.py#L77-L80

You can find the names of the joints in `metadata.xml` (which was taken directly from the Human3.6M website) here: https://github.com/anibali/h36m-fetch/blob/b85e69bb446d5dd87b7461a162a6332654718f3a/metadata.xml#L1421-L2133

**Comment by Droliven** [comment]
Your answer helped me a lot. Thank you.

**Comment by lvandoit** [comment]
hi:
  sorry for bother, I am also interesting in the human pose estimation with human 3.6m as the training dataset. I want to know if the coordinates of these joints are in what coordinate system (camera coordinate system or world coordinate system, where is the origin of coordinates?). And are they in millimeters? @anibali @Droliven

**Comment by lvandoit** [comment]
I want to know what coordinates are these joints in? (Camera coordinates or world coordinates, where is the origin of the coordinates?) And are they in millimeters? @Droliven

**Comment by anibali** [comment]
@lvandoit See https://github.com/anibali/h36m-fetch/issues/16#issuecomment-646345120. 3D coordinates are in mm. 2D coordinates are in pixels (image space).

**Comment by lvandoit** [comment]
@anibali thanks
