### ISSUE TITLE
What's the "Site" of the 32 joints in Poses_D2_Positions_S1?

### ISSUE THREAD

**Issue by Droliven** [anibali/h36m-fetch#21]
I ran the code in the official website and checked 32 joints, but I don't know what's the meaning of 7 "site" joints ? What parts of the body do they belong to?
![1](https://user-images.githubusercontent.com/37187316/84621256-b3d88000-af0c-11ea-98d2-c3b7b99751ae.PNG)
![2](https://user-images.githubusercontent.com/37187316/84621270-b935ca80-af0c-11ea-978a-26bd897a618c.PNG)

**Comment by anibali** [comment]
I'm not sure, I don't use those joints for anything in my own work. You can always look at a few examples to try and figure it out for yourself.

**Comment by Droliven** [comment]
Thank you~
