### ISSUE TITLE
 What is the content of  human3.6m?

### ISSUE THREAD

**Issue by xinzi2018** [anibali/h36m-fetch#25]
can i directly download the human3.6m use "https://drive.google.com/drive/folders/1kgVH-GugrLoc9XyvP6nRoaFpw3TmM5xK?usp=sharing"?     Is the content  the same as your h36m ?

**Comment by anibali** [comment]
No, that has been processed in some other way.

**Comment by xinzi2018** [comment]
我用上面链接下载下来的数据  处理出来了bvh 文件。但此时有个疑问  您官网下载下来的bvh 人初始动作的朝向是+y轴嘛？
