### ISSUE TITLE
Processing all frames in process_all.py

### ISSUE THREAD

**Issue by jamalknight** [anibali/h36m-fetch#28]
The `process_all.py` script processes every 64th frame for the subjects 'S9' and 'S11' in lines:
```
  if subject == 'S9' or subject == 'S11':
        return np.arange(0, len(poses_3d_univ), 64)
```
How can I change the above code to process **all** frames, without skipping any?

Tried: Replacing `64` with `1` and `all` but did not work

**Comment by anibali** [comment]
It should just be a matter of replacing

https://github.com/anibali/h36m-fetch/blob/b8112ff5525aa4ddddabd4c7f629df6752edad20/process_all.py#L39

with

```python
        return np.arange(0, len(poses_3d_univ))
```

**Comment by jamalknight** [comment]
great, thanks
