### ISSUE TITLE
What's the difference between Directions 1.54138969 and Directions.54138969

### ISSUE THREAD

**Issue by Fangyh09** [anibali/h36m-fetch#3]
Hi, I saw there are plenty of duplicated videos. What's the difference between Directions 1.54138969 and Directions.54138969?
https://github.com/anibali/h36m-fetch/blob/4ae1238027f02b37701b1022397020799b63565d/process_all.py#L99-L100

**Comment by anibali** [comment]
These are subactions for the same action, so they are not duplicates but they can be quite similar. Currently I select just a single subaction per action to keep. However, Directions.54138969.mp4 seems to be corrupted, so I use Directions 1.54138969.mp4 instead for that particular sequence.

**Comment by anibali** [comment]
I'm going to reopen this issue, because I want to implement a way of keeping both subactions for each action.

**Comment by Fangyh09** [comment]
I have implemented it. Maybe I could push a request.
