### ISSUE TITLE
Failed to verify your PHPSESSID

### ISSUE THREAD

**Issue by YunYang1994** [anibali/h36m-fetch#31]
╰─➤  python download_all.py
Could not read PHPSESSID from `config.ini`.
Enter PHPSESSID: YunYang
Traceback (most recent call last):
  File "download_all.py", line 106, in <module>
    verify_phpsessid(phpsessid)
  File "download_all.py", line 59, in verify_phpsessid
    assert resp.url == test_url, fail_message
AssertionError: Failed to verify your PHPSESSID. Please ensure that you are currently logged in at http://vision.imar.ro/human3.6m/ and that you have copied the PHPSESSID cookie correctly.

**Comment by anibali** [comment]
You must enter your PHPSESSID, not your username.
Please follow the instructions here: https://github.com/anibali/h36m-fetch#usage
