### ISSUE TITLE
About Frame sampling

### ISSUE THREAD

**Issue by GeniusPatrick** [anibali/h36m-fetch#33]
In `process_all.py` why `frames = frame_indices + 1`?
Why frame indices begin from 1? not 0?
Thanks!

**Comment by anibali** [comment]
I did that to be consistent with the other dataset I was using (MPI-INF-3DHP). In 3DHP, the first image in the test set is called `img_000001.jpg`.

I'm sure that you won't have any difficulty subtracting 1 from the frame numbers if that's what you want :wink:

**Comment by GeniusPatrick** [comment]
Thanks for your reply. Can you share sampled frames' index? I am reproducing a paper using your tools. I want to maintain data consistency and use exactly the same selected frames. I don’t have the original data so I can’t use your script directly, Just the index of the frame after sampling is all I need. Thank you!

**Comment by anibali** [comment]
Here's a list of all of the .jpg file names produced by `process_all.py`: [image_filenames.txt.gz](https://github.com/anibali/h36m-fetch/files/5551333/image_filenames.txt.gz)

**Comment by GeniusPatrick** [comment]
Thank you very very much. You really helped me a lot.
