### ISSUE TITLE
Where can I find the extrinsic parameters?

### ISSUE THREAD

**Issue by lcit** [anibali/h36m-fetch#35]
Thank you for providing this useful fetcher! I want to project the 3d poses into the image however I could not find the extrinsic parameters to do so. Would you be able to provided that as well?

**Comment by lcit** [comment]
I just realized that the 3d poses are in camera coordinate. This means I can project them to the image using just the intrinsics. 
In case anyone is interested I took the extrinsics from here: https://github.com/karfly/human36m-camera-parameters/blob/master/camera-parameters.json

**Comment by zhr-xjtu** [comment]
@lcit I have a question. Does human3.6m data set contain camera parameter information? In the download file, there are 8 cdf files for each action in D3_position_mono_universal. What do they mean? cdf stores 3D coordinates. What is HZ? How does it correspond to video?
