### ISSUE TITLE
"Invalid cross-device link" error from process_all.py

### ISSUE THREAD

**Issue by anibali** [anibali/h36m-fetch#53]
![image](https://user-images.githubusercontent.com/28781249/135067139-4d47ea9a-b9d5-4fd5-ab2d-63414b3b412e.png)
![image](https://user-images.githubusercontent.com/28781249/135067408-88400b74-7bc0-4587-a8d5-6a7c97888df5.png)
Excuse me, sir, I need help! I allow process in this place_ There is a problem with all.py. Cut the pictures that are not cropped out in the corresponding folder (S11)

_Originally posted by @HOH980820 in https://github.com/anibali/h36m-fetch/issues/52#issuecomment-929047831_

**Comment by anibali** [comment]
I believe that this can happen if `/tmp` is located on a different file system to the destination directory (`processed/`). Try replacing this code:

https://github.com/anibali/h36m-fetch/blob/99a723f5fbd2a5f00766385b84ad157871005d5f/process_all.py#L117-L120

with this code:

```python
                import shutil
                move(
                    path.join(tmp_dir, filename),
                    path.join(frames_dir, filename),
                    copy_function=shutil.copy
                )
```

Let me know if this works for you.

**Comment by Jungduri** [comment]
Same issue here. Your suggestion works for me. Thank you a lot.
