### ISSUE TITLE
Account creation on http://vision.imar.ro/human3.6m/ 

### ISSUE THREAD

**Issue by sotomotocross** [anibali/h36m-fetch#54]
I am trying for the last 15 days to access the dataset. I have created an account on the site but no one has yet grant me access to the dataset.
Do you know what applies to this site? Is it active? Has anyone recently managed to download the dataset as described in the Usage section?

Looking forward for your reply and help.

**Comment by anibali** [comment]
I have nothing to do with granting access to the Human3.6M dataset, I just created these scripts to make downloading and extracting the data easier.

**Comment by Billccx** [comment]
> I am trying for the last 15 days to access the dataset. I have created an account on the site but no one has yet grant me access to the dataset. Do you know what applies to this site? Is it active? Has anyone recently managed to download the dataset as described in the Usage section?
> 
> Looking forward for your reply and help.

Hello. Do you have the access to the dataset now?
