### ISSUE TITLE
I get error with Axel when using download_all.py

### ISSUE THREAD

**Issue by phuvm72** [anibali/h36m-fetch#57]
Hi, thanks for your repo. I've been trying to use your code to fetch the data. However, I encounter the error:
`FileNotFoundError: [Errno 2] No such file or directory: 'axel'
`
I double-checked the file directory. Do you know what caused this issue? Thanks

**Comment by anibali** [comment]
axel is a program for downloading files that you need to have installed. See here: https://github.com/axel-download-accelerator/axel
