### ISSUE TITLE
Package resolution with current requirements

### ISSUE THREAD

**Issue by dreavjr** [anibali/h36m-fetch#61]
Pip is having a hard time resolving the dependencies in current requirements.txt. I'd suggest a more permissive one, or an entirely frozen one, with all versions already resolved.

**Comment by anibali** [comment]
I've weakened a couple of the dependencies that have stable APIs and this seems to help. See https://github.com/anibali/h36m-fetch/commit/507e7334681a8a6c63c0b10a46449c4b99ea5a1c. Thanks for posting the issue.
