### ISSUE TITLE
Generated 3D poses in World Coordinate System or Camera Coordinate System?

### ISSUE THREAD

**Issue by ShazibRauf** [anibali/h36m-fetch#63]
The 3D poses generated after compiling the process_all.py file generate poses in the World Coordinated System or Camera Coordinated System?

**Comment by anibali** [comment]
Please see https://github.com/anibali/h36m-fetch/issues/16 and https://github.com/anibali/h36m-fetch/blob/master/process_all.py. We use the "mono" (camera space) coordinates.
