### ISSUE TITLE
PHPSESSID

### ISSUE THREAD

**Issue by GaoChenyuchn** [anibali/h36m-fetch#7]
All people around me haven't the account, so I can't download the dataset. 
Could you give me a PHPSESSID?
Thank you very much!

**Comment by anibali** [comment]
Nope, you have to register at the official website from the creators of the website, here: https://vision.imar.ro/human3.6m/register.php. After you do that, you must log in using your web browser and inspect your cookies to get your PHPSESSID. I am not involved with the management of the dataset at all, I just wrote this tool to make downloading and preprocessing easier.

**Comment by GaoChenyuchn** [comment]
I know, but the website can't be registered now.
